### ISSUE TITLE
Does the guardian has the same height of tower ?

### ISSUE THREAD

**Issue by NinjaPlasma** [Fuzay/ChaosGuardianKiller#21]
I don't know if  the tower are all at the same height

**Comment by ElPilouchador** [comment]
It seems that all the outer towers have the same height.
You should check on your own side to be sure.

On my version they have the same height.

And all the inner towers have the same height wich is around 19-21 blocks.

Hope it will help you !

**Comment by Nicolas62x** [comment]
That’s it but it may depends of the config

**Comment by ghost** [comment]
If it depend on version of minecraft it would be noice to verify on Fuzay version

**Comment by Fuzay** [comment]
Yep, all the towers are the same height (there's actually 2 or 3 sets of towers with different heights that are the same for all the map).

**Comment by Kreoz42** [comment]
Let's imagine we start from a crystal of how much should we advance then how much should we turn to reach another crystal so on

**Comment by ghost** [comment]
Thanks Fuzay im finally in one of your vid

**Comment by Kreoz42** [comment]
someone can help me

**Comment by ttatanepvp123** [comment]
@RafterRed what is your problem ?

**Comment by Kreoz42** [comment]
I can not change the lines of code or write could you please help me @ttatanepvp123

**Comment by ttatanepvp123** [comment]
you must create a fork to make changes

**Comment by Kreoz42** [comment]
What is a fork

**Comment by ttatanepvp123** [comment]
a fork is a copy of the project

**Comment by ttatanepvp123** [comment]
you have to fork with this button and edit on your project then make a pull requests
![image](https://user-images.githubusercontent.com/35320675/54880131-e4348a00-4e41-11e9-8746-371e72a75a5f.png)
(the button is at the top right)
