### ISSUE TITLE
Verify if guardian here 

### ISSUE THREAD

**Issue by NinjaPlasma** [Fuzay/ChaosGuardianKiller#24]
I have alot of option to verify if the guardian is on the island the robot goes:

-(entity verification)
-Make a line of code to make the robot save all the guardian position he killed

**Comment by ghost** [comment]
If you have another idea say it in com for Fuzay

**Comment by Nicolas62x** [comment]
Actualy you just kill them in a line so you don’t have to remember, just go from one to another

**Comment by Fuzay** [comment]
No, the robot should have a way to know if the dragon is alive at the island when it arrives because a player could have killed it.

This mean that saving the guardian the robot killed is not a valid way of knowing wether or not the dragon is alive.

**Comment by ghost** [comment]
Fuzay, you are right because you killed alot of dragon in your video and because you are in Multiplayer, Mr Strikes can come to revenge on you to use his dimension for your rocket

And continue making vid like that :)

**Comment by Nicolas62x** [comment]
Yeah but but how do you do that without loosing more time that you gain in the eventualiti that the boss is already dead

**Comment by Nicolas62x** [comment]
Oh i know how to do it it’s super easy i’ll make a commit
