### ISSUE TITLE
The commits in English or French ?

### ISSUE THREAD

**Issue by ttatanepvp123** [Fuzay/ChaosGuardianKiller#6]
The commits in English or French ?

**Comment by Wistaro** [comment]
English.  
It's better to be understood by everyone.

And Fuze already wrote the README in english btw :)

**Comment by ttatanepvp123** [comment]
yes but in [this](https://github.com/Fuzay/ChaosGuardianKiller/pull/5) pull requests the commit are written in French

**Comment by Wistaro** [comment]
Fuze didn't say anything yet on the language to use in our commits, so he wrote in the language he knew best, the french :D

**Comment by ttatanepvp123** [comment]
I rename the title in English ??

**Comment by Fuzay** [comment]
I'm adding that to the README, commits should be in english
