### ISSUE TITLE
What are the dependencies of the bot?

### ISSUE THREAD

**Issue by ttatanepvp123** [Fuzay/ChaosGuardianKiller#7]
hello, I wonder what must be installed to develop?
because I do not want to install the entire fashion pack.

**Comment by Wistaro** [comment]
Hi.

You must install these mods: 
- OpenComputer Craft
- Draconic Evolution
- Solar Flux Reborn 

And it should works with only these three mods.
But to avoid problems, I recommended you to use the entire modpack (FTB Beyond)

**Comment by ttatanepvp123** [comment]
okay, thanks

**Comment by ttatanepvp123** [comment]
if you want to run without the mod pack.
here is the list of mods with the dependencies :
```bash
BrandonsCore-1.10.2-2.1.11.127-universal.jar
CodeChickenLib-1.10.2-2.5.9.283-universal.jar
Draconic-Evolution-1.10.2-2.1.5.262-universal.jar
HammerCore-1.10.2-1.9.4.3.jar
OpenComputers-MC1.10.2-1.6.2.7.jar
SolarFluxReborn_1.10.2-2.17r.jar
```

**Comment by Wistaro** [comment]
You should close this thread :)

**Comment by Fuzay** [comment]
I'm adding that to the README
