### ISSUE TITLE
Pas de cahier des charges clair

### ISSUE THREAD

**Issue by Ascor8522** [Fuzay/ChaosGuardianKiller#9]
Salut @Fuzay ,

Juste pour dire que les différentes tâches à faire ne sont pas très claires...
Chacun y va de sa façon mais sans but précis. Il faudrait faire une sorte de liste des tâches pour le robot. C'est la meilleure façon de faire avancer le projet.

J'ai essayé de faire un diagramme avec les différents opérations que doit réaliser le robot et j'espère ne rien avoir oublié.

*Cliquez sur l'image pour la voir en plus grand*
![dragon](https://user-images.githubusercontent.com/17651422/54493617-57824d00-48d2-11e9-970f-ef861e81962c.png)

Ca peut aussi servir de base aux autres si ils veulent écrire le programme mais ne savent pas par où commencer...

**Comment by Nicolas62x** [comment]
bah perso j'en suis a un stade ou j'ai besoins de savoir comment on va le tuer ce dragon car mon code est capable du reste car casser les healer avec une épée semble compliqué

**Comment by Fuzay** [comment]
C'est ajouté :)
